Repository TechXpertz/TechXpertz, pull requests merged in 2020-07, with the labels that each got.

#66 Backend reschedule
  backend/controllers/bookings/createBooking.js
  backend/controllers/bookings/deleteBooking.js
  backend/controllers/feedbacks/createFeedback.js
  backend/database.sql
  backend/routes/bookings.js
  backend/routes/feedbacks.js
  backend/server.js
  package-lock.json
  src/api_callers/apis.json
  src/components/Feedback/FeedbackFormPage.js
  src/components/InterviewRoom/CommentSection.js
  src/components/InterviewRoom/Header.js
  src/components/InterviewRoom/InterviewRoom.js
  src/components/InterviewRoom/QuestionBox.js
  src/components/bookingForm/DaysColumn.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/UpcomingInterviewItem.js
Labels: enhancement

#67 get past interviews api
  backend/controllers/bookings/getBookings.js
  backend/controllers/pastInterviews/createPastInterview.js
  backend/controllers/pastInterviews/getPastInterviews.js
  backend/controllers/questions/questions.js
  backend/routes/bookings.js
  backend/routes/questions.js
  src/api_callers/apis.json
  src/components/InterviewRoom/QuestionBox.js
  src/components/dashboard/MainDashboard.js
Labels: enhancement

#72 Backend reschedule
  backend/controllers/bookings/deleteBooking.js
  backend/controllers/bookings/rescheduleBooking.js
  backend/controllers/comments/createComment.js
  backend/database.sql
  backend/routes/bookings.js
  backend/sockets/io.js
  backend/sockets/video.js
  src/api_callers/apis.json
  src/components/App.js
  src/components/InterviewRoom/InterviewRoom.js
  src/components/backendTesting/Video.css
  src/components/backendTesting/Video.js
  src/components/dashboard/CompletedInterviewTable.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/UpcomingInterviewTable.js
Labels: enhancement

#73 Backend reschedule
  backend/controllers/comments/createComment.js
  backend/sockets/comments.js
  src/components/InterviewRoom/CommentSection.js
  src/components/dashboard/MainDashboard.js
Labels: bug

#74 Fixed bug in clicking timeslots in booking form
  src/components/InterviewRequestForm/InterviewRequestForm.js
  src/components/bookingForm/AppointmentScheduler.js
  src/components/bookingForm/DaysColumn.js
  src/components/bookingForm/TimeBlock.js
Labels: bug

#75 Backend reschedule
  backend/config.js
  backend/controllers/pusher/editor.js
  backend/db.js
  backend/routes/pusher.js
  backend/server.js
  package.json
  src/api_callers/apis.json
  src/components/InterviewRequestForm/InterviewRequestForm.js
  src/components/dashboard/ExpertForm.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/NormalForm.js
  src/components/dashboard/UpcomingInterviewTable.js
Labels: enhancement

#77 Backend reschedule
  backend/controllers/bookings/getBookings.js
  backend/controllers/pastInterviews/getPastInterviews.js
  backend/server.js
  package-lock.json
  package.json
  src/auth_config.json
  src/components/InterviewRoom/CodeEditor.js
  src/components/InterviewRoom/CommentSection.js
  src/components/backendTesting/Video.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/UpcomingInterviewTable.js
  src/index.js
  yarn.lock
Labels: bug, enhancement

#80 Backend reschedule
  backend/clockProcess/clock.js
  backend/clockProcess/worker.js
  backend/db.js
  backend/server.js
  package-lock.json
  package.json
  procfile
  src/components/InterviewRequestForm/UpdateInterviewRequestForm.js
  src/components/dashboard/NormalForm.js
Labels: bug

#83 Backend reschedule
  Procfile
  backend/clockProcess/clock.js
  backend/clockProcess/worker.js
  backend/controllers/users/getBackgrounds.js
  backend/routes/user.js
  backend/sockets/comments.js
  backend/workers/testWorker.js
  backend/workers/worker.js
  procfile
  src/api_callers/apis.json
  src/components/InputBox.js
  src/components/dashboard/ExpertForm.js
  src/components/userprofile/ProfileContent.js
Labels: enhancement

#86 Fixed questions and switch role communications
  backend/sockets/comments.js
  backend/sockets/io.js
  backend/sockets/question.js
  backend/sockets/video.js
  src/components/InterviewRoom/CodeEditor.js
  src/components/InterviewRoom/CommentSection.js
  src/components/InterviewRoom/InterviewRoom.js
  src/components/InterviewRoom/QuestionBox.js
  src/components/InterviewRoom/VideoComponent.js
  src/components/dashboard/UpcomingInterviewTable.js
Labels: enhancement

#88 Backend reschedule
  backend/controllers/bookings/createBooking.js
  backend/controllers/bookings/expertActions.js
  backend/controllers/matching/expertMatching.js
  backend/controllers/matching/hopcroftKarp.js
  backend/controllers/matching/matching.js
  backend/controllers/matching/preprocess.js
  backend/controllers/users/accountType.js
  backend/controllers/users/helper.js
  backend/database.sql
  backend/routes/user.js
  backend/setup-instructions.txt
  backend/tests/matching/matchAlgo.js
  backend/tests/matching/preprocess.js
  backend/tests/workers/task.js
  package-lock.json
  package.json
  src/api_callers/apis.json
  src/components/dashboard/MainDashboard.js
Labels: enhancement

#90 Backend reschedule
  backend/controllers/bookings/expertActions.js
  backend/controllers/bookings/getBookings.js
  backend/controllers/users/editBackground.js
  backend/controllers/users/submitBackground.js
  backend/routes/bookings.js
  backend/routes/user.js
  src/components/dashboard/MainDashboard.js
Labels: enhancement

#96 Backend reschedule
  backend/controllers/interviewRoom/roles.js
  backend/controllers/users/username.js
  backend/database.sql
  backend/routes/user.js
  backend/sockets/question.js
  src/api_callers/apis.json
  src/components/InterviewRoom/CommentSection.js
  src/components/InterviewRoom/InterviewRoom.js
  src/components/InterviewRoom/SubHeader.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/UpcomingInterviewTable.js
Labels: bug

#105 Fixed cancel prog language bug
  src/components/InterviewRequestForm/InterviewRequestForm.js
  src/components/InterviewRequestForm/UpdateInterviewRequestForm.js
Labels: bug

#111 Backend reschedule
  src/components/dashboard/MainDashboard.js
Labels: bug

#112 Fixed loading bugs
  src/components/InterviewRequestForm/InterviewRequestForm.js
  src/components/InterviewRequestForm/UpdateInterviewRequestForm.js
  src/components/dashboard/MainDashboard.js
Labels: bug

#113 Fixed delete
  src/components/dashboard/MainDashboard.js
  src/react-auth0-spa.js
Labels: bug

#114 Backend reschedule
  src/components/dashboard/MainDashboard.js
Labels: bug
