Repository TechXpertz/TechXpertz, pull requests merged in 2020-06, with the labels that each got.

#5 Update README
  README.md
Labels: documentation

#11 Backend authentication APIs
  backend/.sample-env
  backend/config.js
  backend/controllers/middleware.js
  backend/controllers/users.js
  backend/database.sql
  backend/node_modules/express-jwt-authz/.prettierrc
  backend/node_modules/express-jwt-authz/.travis.yml
  backend/node_modules/express-jwt-authz/Changelog.md
  backend/node_modules/express-jwt-authz/LICENSE
  backend/node_modules/express-jwt-authz/README.md
  backend/node_modules/express-jwt-authz/lib/index.js
  backend/node_modules/express-jwt-authz/package.json
  backend/node_modules/express-jwt-authz/test/index.tests.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/setup-instructions.txt
Labels: enhancement

#12 Adding BE updates to integrate-auth branch
  backend/.sample-env
  backend/config.js
  backend/controllers/middleware.js
  backend/controllers/users.js
  backend/database.sql
  backend/node_modules/express-jwt-authz/.prettierrc
  backend/node_modules/express-jwt-authz/.travis.yml
  backend/node_modules/express-jwt-authz/Changelog.md
  backend/node_modules/express-jwt-authz/LICENSE
  backend/node_modules/express-jwt-authz/README.md
  backend/node_modules/express-jwt-authz/lib/index.js
  backend/node_modules/express-jwt-authz/package.json
  backend/node_modules/express-jwt-authz/test/index.tests.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/setup-instructions.txt
Labels: enhancement

#13 Integrated FE and BE for authentication
  backend/config.js
  backend/controllers/middleware.js
  backend/controllers/users.js
  backend/routes/auth.js
  backend/server.js
  backend/setup-instructions.txt
  package-lock.json
  package.json
  src/api_callers/apis.json
  src/api_callers/backend_api.js
  src/auth_config.json
  src/components/App.js
  src/components/callback.js
  src/index.js
Labels: enhancement

#26 Update README.md
  README.md
Labels: documentation

#24 Expert background form api
  backend/.gitignore
  backend/controllers/auth/register.js
  backend/controllers/bookings/createBooking.js
  backend/controllers/info.js
  backend/controllers/users/dashboard.js
  backend/controllers/users/helper.js
  backend/controllers/users/submitAccType.js
  backend/controllers/users/submitBackground.js
  backend/database.sql
  backend/routes/auth.js
  backend/routes/bookings.js
  backend/routes/info.js
  backend/routes/user.js
  package-lock.json
  yarn.lock
Labels: enhancement

#28 Integration
  backend/config.js
  backend/controllers/info.js
  backend/controllers/matching/cron.js
  backend/controllers/matching/graph.js
  backend/controllers/matching/helper.js
  backend/controllers/matching/matching.js
  backend/controllers/matching/preprocess.js
  backend/controllers/matching/testing/graph.test.js
  backend/controllers/matching/testing/preprocess.test.js
  backend/package.json
  backend/server.js
  backend/tests/auth.test.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/callback.js
  src/components/dashboard/ExpertForm.js
  src/components/dashboard/NormalForm.js
  src/components/dashboard/UserDashboard.js
Labels: enhancement

#40 Booking integration
  .gitignore
  backend/controllers/bookings/createBooking.js
  backend/controllers/bookings/deleteBooking.js
  backend/controllers/bookings/getBookings.js
  backend/controllers/cronJobs/cronHelpers.js
  backend/controllers/cronJobs/schedule.js
  backend/controllers/socket/auth.js
  backend/controllers/users/hasSubmittedForm.js
  backend/controllers/users/submitBackground.js
  backend/routes/bookings.js
  backend/routes/user.js
  backend/server.js
  backend/tests/cron/scheduleHourly.test.js
  backend/tests/cron/task.test.js
  package-lock.json
  package.json
  src/api_callers/apis.json
  src/components/App.js
  src/components/InterviewRequestForm/InterviewRequestForm.js
  src/components/backendSocket/chat.js
  src/components/backendSocket/message.js
  src/components/backendSocket/prechat.js
  src/components/bookingForm/DaysColumn.js
  src/components/dashboard/ExpertForm.js
  src/components/dashboard/MainDashboard.js
  src/components/dashboard/NormalForm.js
  src/components/dashboard/TypeCheckForm.js
  src/components/dashboard/UpcomingInterviewItem.js
  src/components/dashboard/UserDashboard.js
Labels: enhancement

#41 added socket
  backend/.env
  backend/.gitignore
  backend/config.js
  backend/controllers/bookings/deleteBooking.js
  backend/controllers/bookings/getBookings.js
  backend/controllers/cronJobs/email.js
  backend/controllers/cronJobs/schedule.js
  backend/controllers/cronJobs/tasks.js
  backend/controllers/pusher/editor.js
  backend/routes/pusher.js
  backend/server.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/backendTesting/pusher/codeEditor.js
  src/components/backendTesting/socket/SocketEditor.js
  src/components/backendTesting/socket/chat.js
  src/components/backendTesting/socket/message.js
  src/components/backendTesting/socket/prechat.js
  src/components/dashboard/MainDashboard.js
Labels: enhancement

#45 integrated socket and fixed login
  backend/controllers/bookings/getBookings.js
  backend/controllers/matching/settingMatch.js
  backend/controllers/questions/questions.js
  backend/sockets/comments.js
  backend/sockets/editor.js
  backend/sockets/io.js
  src/components/App.js
  src/components/InterviewRoom/CodeEditor.js
  src/components/InterviewRoom/CommentSection.js
  src/components/InterviewRoom/Header.js
  src/components/InterviewRoom/InterviewRoom.css
  src/components/InterviewRoom/InterviewRoom.js
  src/components/InterviewRoom/QuestionBox.js
  src/components/backendTesting/socket/chat.js
  src/components/backendTesting/socket/message.js
  src/components/backendTesting/socket/prechat.js
  src/components/bookingForm/AppointmentScheduler.js
  src/components/callback.js
  src/components/dashboard/UpcomingInterviewItem.js
  src/components/dashboard/UserDashboard.js
Labels: bug, enhancement

#48 Add additional set up instructions
  README.md
Labels: documentation
